# Generated by Django 5.1.6 on 2025-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='bmi_test',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
