# Generated by Django 5.1.6 on 2025-02-12 11:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter Your Height In Cm', max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter Your Weight In Kg', max_digits=4)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
