# Generated by Django 5.1.6 on 2025-02-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fitnessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
