# Generated by Django 5.1.6 on 2025-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fitnessprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Enter Your Height In Cm', max_digits=6),
        ),
    ]
